// Sound effects for the Game Screen. Plain module (no React) so both the UI and
// any caller share one source of truth for the mute preference and one set of
// audio elements.
//
// Offline-first: the clips are local WAV assets under /sounds (bundled by Vite,
// generated by scripts/gen-sounds.mjs) — no network, no Web Audio graph to fail.
// play() is fire-and-forget and swallows the autoplay rejection browsers throw
// before the first user gesture, so nothing errors on load.

export const MUTE_KEY = 'spacerace:muted'

const SOURCES = {
  correct: '/sounds/correct.wav',
  incorrect: '/sounds/incorrect.wav',
  win: '/sounds/win.wav',
}

// Lazily created <audio>-equivalent elements, one per clip, reused across plays.
// Guarded for non-browser (test) environments where Audio is undefined.
const cache = {}
const elementFor = (name) => {
  if (typeof Audio === 'undefined') return null
  if (!cache[name]) {
    const el = new Audio(SOURCES[name])
    el.preload = 'auto'
    cache[name] = el
  }
  return cache[name]
}

export const isMuted = () => {
  try {
    return localStorage.getItem(MUTE_KEY) === 'true'
  } catch {
    return false
  }
}

export const setMuted = (muted) => {
  try {
    localStorage.setItem(MUTE_KEY, String(muted))
  } catch {
    // ignore storage failures (private mode, etc.) — mute just won't persist
  }
}

// Plays a named effect unless muted. Rewinds first so rapid repeats retrigger.
// Returns the play() promise (or undefined) for tests; never throws.
export const play = (name) => {
  if (isMuted() || !SOURCES[name]) return undefined
  const el = elementFor(name)
  if (!el) return undefined
  try {
    el.currentTime = 0
    // Browsers reject play() until a user gesture has occurred; ignore that so
    // no "autoplay" error surfaces.
    return el.play()?.catch(() => {})
  } catch {
    return undefined
  }
}
